import XCTest
@testable import Proofed

/// Golden values generated by running the reference web calculator's formulas (dg-calculator.js).
final class DoughCalculatorTests: XCTestCase {
    private func run(_ size: Int, _ count: Int, _ t: Thickness = .regular, gf: Bool = false) -> DoughResult {
        DoughCalculator.calculate(DoughInput(sizeInches: size, count: count, thickness: t, glutenFree: gf))
    }

    private func amounts(_ r: DoughResult) -> [String] { r.ingredients.map(\.amount) }

    func testDefaultRegular() {
        let r = run(16, 6)
        XCTAssertEqual(r.ballGrams, 480)
        XCTAssertEqual(r.flourGrams, 1705)
        XCTAssertEqual(r.waterGrams, 1057)
        XCTAssertEqual(r.hydrationPercent, 62)
        XCTAssertEqual(amounts(r), ["1705", "1057", "6.8", "43", "34", "56"])
        XCTAssertNil(r.tip)
    }

    func testGlutenFree() {
        let r = run(16, 6, gf: true)
        XCTAssertEqual(r.ballGrams, 562)
        XCTAssertEqual(amounts(r), ["1998", "1598", "8.0", "50", "40", "66"])
        XCTAssertEqual(r.hydrationPercent, 80)
        XCTAssertEqual(r.tip?.title, "Gluten-free")
    }

    func testThinSingleSmall() {
        let r = run(10, 1, .thin)
        XCTAssertEqual(r.ballGrams, 160)
        XCTAssertEqual(amounts(r), ["95", "59", "0.4", "2", "2", "3"])
        XCTAssertEqual(r.tip?.title, "Thin crust")
    }

    func testThickLargeBatch() {
        let r = run(20, 10, .thick)
        XCTAssertEqual(r.ballGrams, 977)
        XCTAssertEqual(amounts(r), ["5787", "3588", "23.1", "145", "116", "191"])
        XCTAssertEqual(r.tip?.title, "Large pizza")   // size tip outranks batch and thickness
    }

    func testSmallBatch() {
        let r = run(12, 2)
        XCTAssertEqual(r.ballGrams, 270)
        XCTAssertEqual(amounts(r), ["320", "198", "1.3", "8", "6", "11"])
    }

    func testJSRoundHalvesGoUp() {
        XCTAssertEqual(DoughCalculator.jsRound(2.5), 3)
        XCTAssertEqual(DoughCalculator.jsRound(3.5), 4)
    }
}
